//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
	using System.Collections.Generic;

	public partial class Collocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collocation()
        {
            this.Examples = new List<Example>();
        }
    
        public long Id { get; set; }
        public short posId { get; set; }
        public short colPosId { get; set; }
        public long wordId { get; set; }
        public long colWordId { get; set; }
        public int CollocationPattern { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ColPos ColPos { get; set; }
        public virtual ColWord ColWord { get; set; }
        public virtual Pos Pos { get; set; }
        public virtual Word Word { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Example> Examples { get; set; }

		public virtual string ColWordZhs { get; set; }
		public virtual string WordZht { get; set; }
		public virtual string WordZhs { get; set; }
		public virtual string ColWordZht { get; set; }
		public virtual string WordJap { get; set; }
		public virtual string ColWordJap { get; set; }
		public virtual string PosZht { get; set; }
		public virtual string ColPosZht { get; set; }
		public virtual string PosJap { get; set; }
		public virtual string PosZhs { get; set; }
		public virtual string ColPosJap { get; set; }
		public virtual string ColPosZhs { get; set; }
	}

	public enum CollocationPattern
	{
		noun_verb,
		verb_noun,
		adjective_noun,
		verb_preposition,
		preposition_verb, //not used, but must NOT be deleted; otherwise the current examples in the db cannot be shown...
		adverb_verb,
		phrase_noun,
		preposition_noun,
	}
}
