//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using BLL.Abstract;

namespace BLL
{
	using System.Collections.Generic;

	public partial class ColWord:WcBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColWord()
        {
            this.Collocations = new HashSet<Collocation>();
			this.CanDel = true;
		}
    
        public new long Id { get; set; }
        //public string Entry { get; set; }
        //public string EntryZht { get; set; }
        //public string EntryZhs { get; set; }
        //public string EntryJap { get; set; }
        //public byte[] RowVersion { get; set; }
        //public Nullable<bool> CanDel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collocation> Collocations { get; set; }
    }
}
