//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using BLL.Abstract;

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Example:WcBase
    {
        public new long Id { get; set; }
        //public string Entry { get; set; }
        //public string EntryZht { get; set; }
        //public string EntryZhs { get; set; }
        //public string EntryJap { get; set; }
        public string Source { get; set; }
        public string RemarkZht { get; set; }
        public string RemarkZhs { get; set; }
        public string RemarkJap { get; set; }
        public long CollocationId { get; set; }
        //public byte[] RowVersion { get; set; }
    
        public virtual Collocation Collocation { get; set; }
    }
}
