//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using THResources;

namespace BLL
{
	using System.Collections.Generic;

	public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.UserInRoles = new HashSet<UserInRole>();
        }

		[Key]
		[ScaffoldColumn(false)]
		public string Code { get; set; }

		[Required(AllowEmptyStrings = false, ErrorMessageResourceName = "RoleNameRequired", ErrorMessageResourceType = typeof(Resources))]
		[Display(Name = "Role")]
		public string Name { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInRole> UserInRoles { get; set; }
    }
}
