//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WordCollocationEntities : DbContext
    {
        public WordCollocationEntities()
            : base("name=WordCollocationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collocation> Collocations { get; set; }
        public virtual DbSet<ColPos> ColPos { get; set; }
        public virtual DbSet<ColWord> ColWords { get; set; }
        public virtual DbSet<Example> Examples { get; set; }
        public virtual DbSet<Pos> Pos { get; set; }
        public virtual DbSet<Word> Words { get; set; }
    }
}
