//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class collocation
    {
        public collocation()
        {
            this.examples = new HashSet<example>();
        }
    
        public long Id { get; set; }
        public long wordId { get; set; }
        public long colWordId { get; set; }
        public int CollocationPattern { get; set; }
        public System.DateTime RowVersion { get; set; }
    
        public virtual word colword { get; set; }
        public virtual word word { get; set; }
        public virtual ICollection<example> examples { get; set; }
    }

	/*
	 * const NOUN_VERB=1;
	const VERB_NOUN=2;
	const ADJECTIVE_NOUN=3;
	const VERB_PREPOSITION=4;
	this 5 is unused, but must not be deleted; otherwise the current examples in the db cannot be shown... 
	const PREPOSITION_VERB= 5;
	const ADVERB_VERB= 6;
	const PHRASE_NOUN= 7;
	const PREPOSITION_NOUN= 8;
	const ADJECTIVE_PHRASE= 9;
	 */
	public enum CollocationPattern
	{
		noun_verb=1,
		verb_noun=2,
		adjective_noun=3,
		verb_preposition=4,
		preposition_verb=5, //not used, but must NOT be deleted; otherwise the current examples in the db cannot be shown...
		adverb_verb=6,
		phrase_noun=7,
		preposition_noun=8,
		adjective_phrase=9,
	}
}
