//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MyWcModel.Abstract;

namespace MyWcModel
{
	using System;
	using System.Collections.Generic;

	public partial class example : WcBase
	{
		public new long Id { get; set; }
		//public string Entry { get; set; }
		//public string EntryZht { get; set; }
		//public string EntryZhs { get; set; }
		//public string EntryJap { get; set; }
		public Nullable<short> Source { get; set; }
		public string Remark { get; set; }
		public long collocationId { get; set; }
		//public Nullable<System.DateTime> RowVersion { get; set; }

		public virtual collocation collocation { get; set; }
	}

	public enum ExampleSource
	{
		OXFORD_COLLOCATIONS_DICTIONARY = 1,
		NEW_DICTIONARY_OF_ENGLISH_COLLOCATIONS = 2,
		NEWSPAPER = 3,
		WEB = 4,
		FICTION = 5,
		OTHERS = 6,
	}
}
