//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MyWcModel.Abstract;

namespace MyWcModel
{
	using System.Collections.Generic;

	public partial class pos:WcBase
    {
        public pos()
        {
            this.words = new HashSet<word>();
        }
    
        public new short Id { get; set; }
        //public string Entry { get; set; }
        //public string EntryZht { get; set; }
        //public string EntryZhs { get; set; }
        //public string EntryJap { get; set; }
        //public System.DateTime RowVersion { get; set; }
        //public Nullable<bool> CanDel { get; set; }
    
        public virtual ICollection<word> words { get; set; }
    }
}
