//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWcModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WordcollocationEntities : DbContext
    {
        public WordcollocationEntities()
            : base("name=WordcollocationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Collocation> collocations { get; set; }
        public DbSet<Example> examples { get; set; }
        public DbSet<Pos> poss { get; set; }
        public DbSet<Word> words { get; set; }
    }
}
